# Generated by Django 4.1 on 2023-09-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileformatter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="infile",
            name="filename",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
