# Generated by Django 4.1 on 2023-09-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileformatter", "0005_alter_infile_f"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infile",
            name="f",
            field=models.FileField(blank=True, null=True, upload_to="./"),
        ),
    ]
