# Generated by Django 4.1 on 2023-09-28 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fileformatter", "0007_alter_infile_f"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InFile",
        ),
    ]
