# Generated by Django 4.1 on 2023-09-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fileformatter", "0008_delete_infile"),
    ]

    operations = [
        migrations.CreateModel(
            name="tablename",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
            ],
        ),
    ]
